config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: "users/registrations"
  }

  root to: "posts#index"

  resources :onboarding, only: [:show, :update]
  get "dashboard", to: "dashboards#index"
  get "dashboard/search", to: "dashboards#search", as: :dashboard_search

  # Health check
  get "up" => "rails/health#show", as: :rails_health_check

  # API routes
  namespace :api do
    get 'reverse_geocode', to: 'geocoding#reverse'
  end

  get :search, to: "pages#search"


  # Defines the root path route ("/")
  # root "posts#index"
  resources :conversations, only: [:index, :show, :create, :destroy, :new] do
    collection do
      post :create_with_user
      get :search
    end
    post :create_events, on: :member  # ✅ ton bouton "✨ Générer 3 événements" utilisera ça
    resources :messages, only: [:create]
    resources :message_users, only: [:create]
  end

    # No route matches [GET] "/events/1/event_participations"

    resources :events, only: [:index, :new, :create, :show, :destroy] do
    post :confirm, on: :member
    resources :event_participations, only: [:create]
    collection do
      get :search
    end
  end

  resources :event_participations, only: [:destroy]
  resources :posts do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end

  # Profile avec gestion de l'avatar
  resources :profiles, only: [:show, :edit, :update,] do
    member do
      delete :delete_avatar
      get :card
    end
  end

  resources :matches, only: [:index, :create]

  # Users are shown via profiles; no separate UsersController needed
  # resources :users, only: [:show]

  get "webmanifest"    => "pwa#manifest"
  get "service-worker" => "pwa#service_worker"
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :event_participations, dependent: :destroy
  has_many :users, through: :event_participations, source: :user
  has_many :participants, through: :event_participations, source: :user
  belongs_to :user

  def starts_at
    value = super
    value.is_a?(String) ? Time.parse(value) : value
  end

  def ends_at
    value = super
    value.is_a?(String) ? Time.parse(value) : value
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:destroy]

  def new
    @event = Event.new
  end

  def create
    @participation = @event.event_participations.new(user: current_user)

    if @participation.save
      redirect_to events_path, notice: "🎉 Tu es inscrit à l'événement '#{@event.title}'"
    else
      redirect_to events_path, alert: "⚠️ Impossible de t'inscrire à cet événement."
    end
  end

  def create_events
    @conversation = Conversation.find(params[:id])

    # Rejouer un prompt spécifique pour demander les events
    ruby_llm_chat = RubyLLM.chat
    build_conversation_history
    ruby_llm_chat.with_instructions("À partir de cette conversation, génère 1 event en JSON { events: [...], proposals: '...' }")

    response = ruby_llm_chat.ask("Propose-moi 1 événement")
    json_response = JSON.parse(response.content)

    events_data = json_response["events"]
    proposals   = json_response["proposals"]

    assistant_message = @conversation.messages.create!(
      content: proposals,
      role: "assistant",
      conversation: @conversation
    )

    events_data.each do |event_attributes|
      event = Event.new(event_attributes)
      event.message = assistant_message
      event.save
    end

    redirect_to @conversation, notice: "3 événements générés ✅"
  end

  def show
    # conversation_message_path	GET	/conversations/:conversation_id/messages/:id(.:format)
    json_response = @assistant_response
    @events = JSON.parse(json_response)

    # @events = Event.all.as_json(only: [:title, :description, :starts_at, :ends_at, :location])
  end

  def index
    @events = Event.all.order(starts_at: :asc)

    if params[:query].present?
      @events = @events.where("title ILIKE :q OR description ILIKE :q OR location ILIKE :q", q: "%#{params[:query]}%")
    end

    return unless params[:date].present?

    date = begin
      Date.parse(params[:date])
    rescue StandardError
      nil
    end
    return unless date

    @events = @events.where("DATE(starts_at) = ?", date)
  end

  def destroy
    if @event.present?
      @event.destroy
      redirect_to events_path, notice: "Événement supprimé ✅"
    else
      redirect_to events_path, alert: "⚠️ Impossible de trouver cet événement."
    end
  end

  def search
    query = params[:query]
    @events = Event.where("title ILIKE ?", "%#{query}%")
    render partial: "dashboards/events_today", locals: { events: @events }
  end

  private

  def event_params
    params.require(:event).permit(:title)
  end

  def set_event
    @event = Event.find(params[:id])
  end
end

app/views/events/index.html.erb
 <% content_for :page_title, "Évènements" %>

    <% content_for :header do %>
      <%= render 'layouts/topbar_header' %>
    <% end %>

<div class="events-page" data-controller="events">
 <!-- Barre de recherche -->
  <div class="search-bar">
    <i class="fa-solid fa-magnifying-glass me-2"></i>
    <input type="text"
           placeholder="Rechercher un événement..."
           data-events-target="searchInput"
           data-action="input->events#search">
  </div>


    <%= button_to conversations_path,
                    method: :post,
                    form: { data: { turbo: false } },
                    class: "p-0 border-0 bg-transparent w-100 text-start" do %>

      <%= render "layouts/infos_card",
            title: "FitBuddy – Créateur d’évènements",
            description: "Crée des évènements sportifs en un instant ! Dis-moi quelle activité tu veux organiser et je t’aide",
            icon: content_tag(:i, "", class: "fa-solid fa-bolt-lightning"),
            bg: "rgba(245, 235, 255, 1)",
            border_gradient: "linear-gradient(90deg, rgba(167, 79, 255, 0.35), rgba(22, 110, 253, 0.35))",
            icon_gradient: "linear-gradient(135deg, rgba(167, 79, 255, 1), rgba(22, 110, 253, 1))"
      %>

    <% end %>

  <!-- Boucle dynamique -->
  <% @events.each do |event| %>
    <div class="event-card" data-events-target="card">
      <div class="event-header d-flex justify-content-between align-items-start">
        <div class="d-flex align-items-center event-title">
          <h3 class="mb-0"><%= event.title %></h3>
        </div>

        <div class="event-date-tag ms-auto">
          <%= l(event.starts_at.to_date, format: "%d %b %Y") %>
        </div>
      </div>
      <p class="event-desc"><%= event.description %></p>
      <ul class="event-info list-unstyled pt-2">
        <li class="d-flex align-items-center">
          <i class="fa-solid fa-location-dot me-2 text-secondary"></i>
          <span><%= event.location %></span>
        </li>
        <li class="d-flex align-items-center">
          <i class="fa-solid fa-users me-2 text-secondary"></i>
          <span>Participants : <%= ["3", "5", "8", "10"].sample %></span>
        </li>

        <% levels = { "débutant" => 1, "intermédiaire" => 2, "avancé" => 3 } %>
        <% current_level_label = ["débutant", "intermédiaire", "avancé"].sample %>
        <% current_level = levels[current_level_label] %>
        <div class="d-flex d-flex justify-content-between w-100 pt-2">
          <li class="d-flex align-items-center gap-2 mt-2">
            <%# <i class="fa-solid fa-signal text-secondary"></i> %>
            <span class="text-capitalize fw-bold"><%= current_level_label %></span>
            <div class="d-flex align-items-center gap-1">
              <% 1.upto(3) do |i| %>
                <div class="level-dot <%= 'active' if i <= current_level %>"></div>
              <% end %>
            </div>
          </li>
          <div class="event-footer">
            <%= turbo_frame_tag dom_id(event, :participation_button) do %>
              <% if current_user.events.include?(event) %>
                <%= button_to "Inscrit ✅",
                              event_participation_path(current_user.event_participations.find_by(event: event)),
                              method: :delete,
                              class: "btn btn-success btn-join-inscrit" %>
              <% else %>
                <%= button_to "S'inscrire",
                              event_event_participations_path(event),
                              method: :post,
                              class: "btn btn-outline-primary btn-join" %>
              <% end %>
            <% end %>

          </div>
        </div>
      </ul>



    </div>
  <% end %>

  <!-- 🌟 Popup global -->
  <div id="signup-popup" class="popup-overlay hidden" data-events-target="popup">
    <div class="popup">
      <div class="popup-header">
        <i class="fa-solid fa-circle-check"></i>
      </div>
      <div class="popup-body">
        <h3>Inscription réussie 🎉</h3>
        <p>Bienvenue parmi nous ! Vous êtes bien inscrit.</p>
      </div>
      <div class="popup-footer">
        <button class="popup-btn" data-action="click->events#closePopup">
          <i class="fa-solid fa-arrow-right"></i>
          <span>Continuer</span>
        </button>
      </div>
    </div>
  </div>
</div>